language: python
python:
  - "3.3"

# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install coveralls --use-mirrors

# command to run tests
script: nosetests tests --with-coverage --cover-inclusive

after_success:
  - coveralls
