language: python
python:
  - "3.3"

# command to install dependencies
install:
  - pip install . --use-mirrors
  - pip install coveralls --use-mirrors

before_script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"

# command to run tests
script: nosetests tests --with-coverage --cover-inclusive

after_success:
  - coveralls
